server.port=${PORT:8080}

spring.application.name=elv
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.100.200:5433/elv?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:elvuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource


spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API Documentation (Swagger/OpenAPI)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html